### ISSUE TITLE
Installation setup file doesn't install "envs" directory

### ISSUE THREAD

**Issue by sweaver2494** [mimoralea/random-walk#1]
When using the specified install instructions, gym_walk is installed without the envs directory. This only allows you to import gym_walk when inside the repo. 

Modify the 'packages' line in the setup.py file from:
`packages=['gym_walk'],`
to:
`packages=['gym_walk', 'gym_walk.envs'],`

This allows you to import gym_walk from anywhere.

**Comment by mimoralea** [comment]
You want to send a pull request?
